### ISSUE TITLE
Pause playback if no pin activity

### ISSUE THREAD

**Issue by whg** [whg/dmx_player#2]
Is it possible to pause the loop as its playing after x seconds since last state change of digital input. It will resume if the state changes. (Someone goes past PIR sensor)

**Comment by whg** [comment]
But do you want it to continually restart when the each time the state changes?

**Comment by star210** [comment]
Thinking about it more... can we have pause on button press, and resume on button press. Its unlikely to have a senario where theres a time out, so thats not needed...

**Comment by whg** [comment]
Same button, yeah?

**Comment by star210** [comment]
Yes please
